/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmproj;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ibrahim ismail
 */
public class FASTCASH extends javax.swing.JFrame {

    /**
     * Creates new form FASTCASH
     */
    public FASTCASH() {
        initComponents();
        scalarIamges();
    }
    int AccNum, OldBalance;
    Connection con1 = null, con = null;
    PreparedStatement pst1 = null, pst = null;
    ResultSet rs1 = null;

    public FASTCASH(int Acc) {
        initComponents();
        scalarIamges();
        AccNum = Acc;
        GetBalance();
    }

    private void scalarIamges() {
        ImageIcon icon = new ImageIcon("D:\\STUDY\\Skills\\codecluse_project\\ATMPROJ\\src\\imges\\ex1.png");
        Image img = icon.getImage();
        Image imscale = img.getScaledInstance(jLabel16.getWidth(), jLabel16.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon iscale = new ImageIcon(imscale);
        jLabel16.setIcon(iscale);

    }

    private void GetBalance() {

        String query = "select * from accounttbl where AccNum = ?";
        try {
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
            pst1 = con1.prepareStatement(query);
            pst1.setInt(1, AccNum);
            rs1 = pst1.executeQuery();

            if (rs1.next()) {
                OldBalance = rs1.getInt("Balance");
                System.out.println(OldBalance);
            } else {
                System.out.println("Error!");

            }
        } catch (SQLException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        j100 = new javax.swing.JLabel();
        j200 = new javax.swing.JLabel();
        j50 = new javax.swing.JLabel();
        others = new javax.swing.JLabel();
        j2000 = new javax.swing.JLabel();
        j4000 = new javax.swing.JLabel();
        j1000 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 71, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FAST CASH");

        j100.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j100.setForeground(new java.awt.Color(255, 255, 255));
        j100.setText("100");
        j100.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j100MouseClicked(evt);
            }
        });

        j200.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j200.setForeground(new java.awt.Color(255, 255, 255));
        j200.setText("200");
        j200.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j200MouseClicked(evt);
            }
        });

        j50.setBackground(new java.awt.Color(255, 255, 255));
        j50.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j50.setForeground(new java.awt.Color(255, 255, 255));
        j50.setText("50");
        j50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j50MouseClicked(evt);
            }
        });

        others.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        others.setForeground(new java.awt.Color(255, 255, 255));
        others.setText("Others");
        others.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        j2000.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j2000.setForeground(new java.awt.Color(255, 255, 255));
        j2000.setText("2000");
        j2000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j2000MouseClicked(evt);
            }
        });

        j4000.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j4000.setForeground(new java.awt.Color(255, 255, 255));
        j4000.setText("4000");
        j4000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j4000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j4000MouseClicked(evt);
            }
        });

        j1000.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        j1000.setForeground(new java.awt.Color(255, 255, 255));
        j1000.setText("1000");
        j1000.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        j1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j1000MouseClicked(evt);
            }
        });

        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("LOGOUT");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(j100, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j1000)
                    .addComponent(j4000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(j200, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(j50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(j2000, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(others, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j100))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j200)
                    .addComponent(j1000))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2000, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j4000))
                .addGap(29, 29, 29)
                .addComponent(others)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(logout))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        this.setVisible(false);
        JFrame back = new HOME();
        back.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMouseClicked

    private void j50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j50MouseClicked
        if (OldBalance < 50) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 50);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:

        // TODO add your handling code here:
    }//GEN-LAST:event_j50MouseClicked

    private void j100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j100MouseClicked
        // TODO add your handling code here:
        if (OldBalance < 100) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 100);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_j100MouseClicked

    private void j200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j200MouseClicked
        if (OldBalance < 200) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 200);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_j200MouseClicked

    private void j1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1000MouseClicked
        // TODO add your handling code here:
         if (OldBalance < 1000) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 1000);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_j1000MouseClicked

    private void j2000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2000MouseClicked
        // TODO add your handling code here:
         if (OldBalance < 2000) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 2000);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_j2000MouseClicked

    private void j4000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j4000MouseClicked
        // TODO add your handling code here:
         if (OldBalance < 4000) {
            JOptionPane.showMessageDialog(null, "There Isn't Enough Money!");
        } else {
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/atmdb", "root", "");
                String sql = "UPDATE accounttbl SET Balance = ? WHERE AccNum=?";
                pst = con.prepareStatement(sql);

                pst.setInt(1, OldBalance - 4000);
                pst.setInt(2, AccNum);
                int r = pst.executeUpdate();
                if (r > 0) {
                    JOptionPane.showMessageDialog(null, "Wait TO Recieve Money!");
                    this.setVisible(false);
                    JFrame h = new HOME();
                    h.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Try Again!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(AddCard.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_j4000MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FASTCASH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FASTCASH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j100;
    private javax.swing.JLabel j1000;
    private javax.swing.JLabel j200;
    private javax.swing.JLabel j2000;
    private javax.swing.JLabel j4000;
    private javax.swing.JLabel j50;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel others;
    // End of variables declaration//GEN-END:variables
}
